### ISSUE TITLE
Set up ScrumDo Integration

### ISSUE THREAD

**Issue by andrewjennings** [PublicMapping/districtbuilder-classic#1]
Let's see how that works.

**Comment by andrewjennings** [comment]
I'm going to write this up in the wiki, which will close Story #128

**Comment by andrewjennings** [comment]
Do I need to say closing Story #128?  ing is cool

**Comment by andrewjennings** [comment]
Oh wait, it's Done in scrumdo for Story #128

**Comment by dzwarg** [comment]
You do realize that this bug makes you look more than just a little odd, right?

**Comment by andrewjennings** [comment]
You don't have to be crazy to code here but it helps. :)

I was testing whether GitHub's ScrumDo integration extended to GitHub comments or only Git commit comments.  Looks as if it's the latter.
