### ISSUE TITLE
Behavior of District Select and Assignment Tools

### ISSUE THREAD

**Issue by mcdisc** [PublicMapping/districtbuilder-classic#126]
If a district selection tools is selected and click and drag assignment is selected, if a set of geographies have been selected bu the user does not wish to assign it, the click and drag must be unselected to select a different set of geographies.

Ideally, selecting another set of geography would automatically deselect the selected geographies.

Alternative method to implement: pressing "esc" de-selects current selection.

**Comment by dzwarg** [comment]
Implemented "ESC" to de-select current selection, and enable selection of geography again, without changing any tools. Commit 4eae4f0
