### ISSUE TITLE
Make configurable district label formatter

### ISSUE THREAD

**Issue by abbyfretz** [PublicMapping/districtbuilder-classic#129]
This is so we can do things such as: remove the "District " from the display if there are an exceptional number of districts and the text is hard to read.

**Comment by dzwarg** [comment]
This is controlled by the "member" attribute of the DistrictBuilder/LegislativeBodies/LegislativeBody configuration item.

**Comment by kshepard** [comment]
The member attribute determines how the district is named throughout the app. In this case, we want to have a minimal label display on the map (the only place where cluttering happens), but keep the longer name elsewhere. As it is now, removing "District " from the member configuration will cause various dropdowns and grid items to only display the number as well.

**Comment by dzwarg** [comment]
Should we break it into 2 settings?
- app_label
- map_label

Or more generically?
- short_label
- long_label

In addition to the map labels, we use the #s only in the sidebars, too.

**Comment by kshepard** [comment]
I like that solution, particularly the short_label/long_label option. And good point on the sidebars: we should switch those to use the new short_label.

**Comment by dzwarg** [comment]
Work began in 4d4ccf0

**Comment by dzwarg** [comment]
The "member" field of legislative bodies has been broken out into "short_label" and "long_label". In addition, the "name" field of districts has likewise been broken out into "short_label" and "long_label".

Fixed in 8be2898
