### ISSUE TITLE
Nested score functions don't work with dictionary results

### ISSUE THREAD

**Issue by kshepard** [PublicMapping/districtbuilder-classic#130]
Since the switch to use dictionaries for results rather than raw values, nested scoring stopped working correctly. This can be demonstrated by configuring a Percent score where the denominator is a reference to a Sum score function.

**Comment by dzwarg** [comment]
This came up in the course of revamping the unit tests, and I suspect that it may be resolved. 

If this can be reproduced, please write a unit test that demonstrates the error.

**Comment by dzwarg** [comment]
See: [NestingTestCase in tests.py](https://github.com/PublicMapping/DistrictBuilder/blob/regionalization/django/publicmapping/redistricting/tests.py#L3504)

**Comment by dzwarg** [comment]
No further noise on this issue, closing as fixed.
