### ISSUE TITLE
setup.py does not generate sld files

### ISSUE THREAD

**Issue by abbyfretz** [PublicMapping/districtbuilder-classic#132]
As discussed with David. This came as a surprise to me and to Michael -- we thought setup was supposed to do everything necessary to create an instance once supplied with appropriate data and config files.

I'm hacking up something to spit these out based on quantiles for every variable, but this really should be driven by the config file (e.g. specifying which vars to use for geounit choropleths, specifying either number of quantiles or specific values for breakpoints).

**Comment by maltman** [comment]
As part of the add/modify subject task we agreed that appropriate SLD's would be generated. Our assumption was that they these would also be generated if subjects were added through setup.py. However, its not clear from the setup.py code that this is happening.

**Comment by dzwarg** [comment]
Added in 8e07017f9cc4b820aa31039e98fa28a3e290af71
