### ISSUE TITLE
New blank map after zoom in shows map data not yet available

### ISSUE THREAD

**Issue by maltman** [PublicMapping/districtbuilder-classic#185]
Restarting browser eliminated issue, but shouldn't happen:

see http://www.box.net/shared/ma9gcj2tsvor5p3kdymv

**Comment by andrewjennings** [comment]
Looks as if the zoom level went in farther than the base map can handle.  Can you please explain how to reproduce this bug?  Which tool you used to zoom, whether you switched tools, etc.  I can't reproduce it using the slider or my mouse wheel.

**Comment by maltman** [comment]
Hmm. I'd used a two mouse-wheel (actually two finger gesture on OS X)
to zoom. But now that I've logged out I can't reproduce. Maybe there
is a race condition?

On Fri, Oct 14, 2011 at 10:56 AM, Andrew Jennings
reply@reply.github.com
wrote:

> Looks as if the zoom level went in farther than the base map can handle.  Can you please explain how to reproduce this bug?  Which tool you used to zoom, whether you switched tools, etc.  I can't reproduce it using the slider or my mouse wheel.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/PublicMapping/DistrictBuilder/issues/185#issuecomment-2407498

## 

---

Micah Altman, Ph.D. http://redistricting.info           Twitter: @drmaltman
Senior Research Scientist, Institute for Quantitative Social Science, Harvard U.
Archival Director, Henry A. Murray Archive;
"Entia non sunt multiplicanda sine necessitate" - Dr. Invincibilis
(Corollary, "Ad indicia spectate.")

**Comment by maltman** [comment]
Not reproducible.
