### ISSUE TITLE
Javascript Error on Home page under IE8

### ISSUE THREAD

**Issue by maltman** [PublicMapping/districtbuilder-classic#186]
See http://www.box.net/shared/vixng8u5e6p06qde786d

**Comment by kshepard** [comment]
I'm not able to reproduce this in IE8. 'stLight' is referring to the ShareThis widget, however. This widget was recently switched over to use a secure url. Maybe your browser still has the old code cached? Would you be able to clear out your cache and try again?

**Comment by maltman** [comment]
Perhaps. Can't reproduce now. - Micah

**Comment by maltman** [comment]
Not reproducible in current version
