### ISSUE TITLE
UI - Choosing a region from the Plan Chooser

### ISSUE THREAD

**Issue by abbyfretz** [PublicMapping/districtbuilder-classic#189]
The user can select a region from the plan chooser.  A user can edit only plans in a region at a time.  If no regions are present, only legislative bodies should show up.  The leaderboard should also have a drop-down for regions

**Comment by dzwarg** [comment]
Quick hack: the region name is prepended to the legislative body in the plan chooser.  If this is sufficient and clear, then I say we go for it.

Added in 7203a467d5176ac57d8e15f3c08c78a2638d13c4
