### ISSUE TITLE
Support Regionlization in Mapping interface

### ISSUE THREAD

**Issue by abbyfretz** [PublicMapping/districtbuilder-classic#191]
Maps should zoom correctly to a region, users should only be able to choose options/stats applicable to their region, etc.

**Comment by andrewjennings** [comment]
Most of this stuff is taken care of at the "geolevel" level.  But we need to update the map layer chooser and the "Currently Viewing" item at the bottom of the page to show a better name for a geolevel since it also has the region appended to it.
