### ISSUE TITLE
Password Cannot be Entered in IE7

### ISSUE THREAD

**Issue by maltman** [PublicMapping/districtbuilder-classic#198]
Haven't tested on other platforms. But when I go to districtbuilder.redistrictny.org in IE7 the password appears as blanks, and a correct password is not accepted. See:

http://www.box.net/shared/p94dzskd357eiltntzjp

**Comment by maltman** [comment]
Still reproducible

**Comment by dzwarg** [comment]
At the current time, we are supporting the following browsers:
- IE 8
- IE 9
- FF 6
- FF 7
- Chrome 13
- Chrome 14
- the two most recent versions of Safari

Closing bug as "won't fix".

**Comment by maltman** [comment]
ok

On Wed, Dec 7, 2011 at 4:03 PM, David Zwarg
reply@reply.github.com
wrote:

> At the current time, we are supporting the following browsers:
> 
>  - IE 8
>  - IE 9
>  - FF 6
>  - FF 7
>  - Chrome 13
>  - Chrome 14
>  - the two most recent versions of Safari
> 
> Closing bug as "won't fix".
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/PublicMapping/DistrictBuilder/issues/198#issuecomment-3053379

## 

---

Micah Altman, Ph.D. http://redistricting.info           Twitter: @drmaltman
Senior Research Scientist, Institute for Quantitative Social Science, Harvard U.
Director of Archiving and Acquisitions, IQSS;
"Entia non sunt multiplicanda sine necessitate" - Dr. Invincibilis
(Corollary, "Ad indicia spectate.")
