### ISSUE TITLE
If both id and e-mail entered in password recovery, only id is used

### ISSUE THREAD

**Issue by maltman** [PublicMapping/districtbuilder-classic#199]
E-mail recovery only works when the id field is blank (which is by ok), but no error/indication is given when both are entered, and id is sticky which leads to the following confusing scenario:

1)Click on forgot password link on home page 
3)Enter Username to get the hint
4)New Box is open with Hint for your password
5)If user still did not remember pass word, there is message to go back and enter email id 
6) Go back, enter id, click begin. 
7) Still the box is open with Hint and user pass word did not get reset.

**Comment by dzwarg** [comment]
Enhanced the very large "OR" text on the forgotten password dialog in ce67e97

**Comment by maltman** [comment]
Its a minor issue, but changing the font doesn't close it. And technically speaking OR does is not unambiguously interpreted as "exclusive or" ... it can mean "at least one of" And this user was literally following the instructions to go back and enter the e-mail address (the instructions did not say -- go back, clear form, enter e-mail form).   The issue is that the form allows two pieces of data to be entered but ignores one without any feedback to the user. Rather than silently ignoring the second input, slight modifications would be to either allow only one of the fields to be entered (e.g. via JS), explicitly indicate which one is salient (e.g. via a radio button), complete both actions if both fields are entered, or issue a warning that the 2nd piece of information was ignored.

**Comment by dzwarg** [comment]
Task reopened to make the user input to the form exclusive or.

**Comment by maltman** [comment]
Ok, thanks. Again, its a minor issue... just  not a closed one.

On Thu, Oct 27, 2011 at 4:39 PM, David Zwarg <
reply@reply.github.com>wrote:

> Task created to make the user input to the form exclusive or.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/PublicMapping/DistrictBuilder/issues/199#issuecomment-2549020

##
