### ISSUE TITLE
Evaluate on blank plan blows up with python errors

### ISSUE THREAD

**Issue by maltman** [PublicMapping/districtbuilder-classic#201]
Error creating calculator report: Traceback (most recent call last): File "/projects/PublicMapping/DistrictBuilder/django/publicmapping/redistricting/utils.py", line 664, in createcalculatorreport try: File "/projects/PublicMapping/DistrictBuilder/django/publicmapping/redistricting/models.py", line 3019, in render def **unicode**(self): File "/projects/PublicMapping/DistrictBuilder/django/publicmapping/redistricting/models.py", line 3219, in render These computed scores do not store the version number, since ...

etc.

**Comment by kshepard** [comment]
This was caused by a rogue Celery process that wasn't shutting down/restarting when issuing the Celery stop/restart command. It was running an older version of code that didn't have a division by zero check. The process has been killed, and reports work fine now.
