### ISSUE TITLE
Shared plans request slow and interferes with subsequent 'My Plans' request

### ISSUE THREAD

**Issue by abbyfretz** [PublicMapping/districtbuilder-classic#202]
The 'shared plans' request takes a fairly long time to generate a list of just 20 plans (15 seconds). If I click on the "My Plans" tab while the shared plans are still loading, the AJAX calls cross paths and the list of shared plans populate "My Plans" columns/tab.

**Comment by dzwarg** [comment]
Fixed in 645041c36455f6e4455fcacd7b2939f4a33c8ccf. Improved performance by not counting districts of all plans.
