### ISSUE TITLE
Update plans when modifying or deleting subjects

### ISSUE THREAD

**Issue by kshepard** [PublicMapping/districtbuilder-classic#213]
When the subject data changes, plans can no longer be considered valid on the leaderboard, so is_valid needs to be set to False. Also, is_pending needs to be set to True in order to allow the application to know that the plan needs to be re-aggregated.

**Comment by kshepard** [comment]
is_pending has been replaced with processing_state. Should set this to 'Needs reaggregation'.

**Comment by dzwarg** [comment]
Marked all plans as "Needs reaggregation" after Subject upload. Added in 4f8945c9c33a37184499454ce2abdb294885abe2
