### ISSUE TITLE
Update re-nesting command to work with regionalized geolevels

### ISSUE THREAD

**Issue by andrewjennings** [PublicMapping/districtbuilder-classic#217]

**Comment by dzwarg** [comment]
Looking closely at the code, I don't think renesting needs to change at all.

Renesting operates on all the base geolevels (the ones listed in the config at /DistrictBuilder/GeoLevels/GeoLevel), and aggregates the geometric shapes and numerical data values. The relationships of geounits to geolevels are not modified, and the aggregation is in no way affected by the configuration of the regions.

**Comment by dzwarg** [comment]
Ran setup and renesting, and geometries look spot-on. Closing this issue.
