### ISSUE TITLE
Geoserver layers misconfigured after regionalization setup

### ISSUE THREAD

**Issue by dzwarg** [PublicMapping/districtbuilder-classic#223]
The geoserver layers are misconfigured after setup. This causes GWC to return null pointer exceptions. Layers in Geoserver admin interface that do not have a configured SRS cause problems with GWC.

**Comment by dzwarg** [comment]
Seems like the spatial views are not aligned -- they don't point to the correct geolevels?  This might be a problem with a bad import or bad setup script.

**Comment by andrewjennings** [comment]
I think it was a bad import on the postgres DB I dumped.  Will update this issue after a fresh import.

**Comment by dzwarg** [comment]
This went away after nuke & pave of geoserver. GWC was in a foo'd state.
