### ISSUE TITLE
Plan chooser: Request file: Please wait dialog does not display when multiple plans are queued

### ISSUE THREAD

**Issue by maltman** [PublicMapping/districtbuilder-classic#249]
When multiple files are requested, "Please wait" shows only for the last request, "request file" button should be disabled for all plans that are queued. 

See http://www.box.com/s/tjtddpzcru07koe1btlc

**Comment by dzwarg** [comment]
I cannot reproduce this bug. This may have been due to an earlier celery engine failure.

**Comment by maltman** [comment]
Celery failure probably made it easier to see, since plans would be
queued longer (or indefinitely). But still reproducible, see

http://www.box.com/s/ofjpbdm7vnv7jkcoy99c

On Wed, Dec 7, 2011 at 1:59 PM, David Zwarg
reply@reply.github.com
wrote:

> I cannot reproduce this bug. This may have been due to an earlier celery engine failure.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/PublicMapping/DistrictBuilder/issues/249#issuecomment-3051654

## 

---

Micah Altman, Ph.D. http://redistricting.info           Twitter: @drmaltman
Senior Research Scientist, Institute for Quantitative Social Science, Harvard U.
Director of Archiving and Acquisitions, IQSS;
"Entia non sunt multiplicanda sine necessitate" - Dr. Invincibilis
(Corollary, "Ad indicia spectate.")
