### ISSUE TITLE
Export: Print should not take user out of the main interface

### ISSUE THREAD

**Issue by maltman** [PublicMapping/districtbuilder-classic#250]
Export print takes user out of the main interface leaving them on a separate, unadorned page with little context. 

Instead the UI should be handled similarly to "Evaluate" where a print preview is supplied within the main interface.

**Comment by dzwarg** [comment]
As part of the recent PDF improvements, PDFs are now opened in the _blank HTML frame. When PDF layout and styling are complete, change the URL to return a PDF attachment, instead of an HTML preview.

**Comment by maltman** [comment]
great.

On Wed, Dec 14, 2011 at 2:34 PM, David Zwarg
reply@reply.github.com
wrote:

**Comment by maltman** [comment]
Appears completed. Anything left?

**Comment by dzwarg** [comment]
Nope! Closing.
