### ISSUE TITLE
DistrictBuilder logo issues

### ISSUE THREAD

**Issue by maltman** [PublicMapping/districtbuilder-classic#255]
DistrictBuilder logo on inner pages is inconsistent with current logo
- does not use current color scheme/logo
- appears as if "District" and "Builder" are two separate words since they are on separate lines. Confuses branding.
- should link to entry page
- should include "alt" text

**Comment by abbyfretz** [comment]
Designer will add full-length logo, but it will be a single light color that will go well with most designs/color palettes. Will dynamically link to 'home' or 'entry' page and will include alt text.

**Comment by maltman** [comment]
Sounds good.

On Wed, Dec 7, 2011 at 5:12 PM, Abby
reply@reply.github.com
wrote:

> Designer will add full-length logo, but it will be a single light color that will go well with most designs/color palettes. Will dynamically link to 'home' or 'entry' page and will include alt text.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/PublicMapping/DistrictBuilder/issues/255#issuecomment-3054384

## 

---

Micah Altman, Ph.D. http://redistricting.info           Twitter: @drmaltman
Senior Research Scientist, Institute for Quantitative Social Science, Harvard U.
Director of Archiving and Acquisitions, IQSS;
"Entia non sunt multiplicanda sine necessitate" - Dr. Invincibilis
(Corollary, "Ad indicia spectate.")

**Comment by briantjacobs** [comment]
I've updated the logo.
