### ISSUE TITLE
Regionalization: evaluate regionalized plan yields "report error" 

### ISSUE THREAD

**Issue by maltman** [PublicMapping/districtbuilder-classic#256]
Use the plan labeled "test eval" 

Evaluate population. After waiting a few minutes  to generate report app returns "Report Error"

**Comment by dzwarg** [comment]
This may have been a symptom of the celery process crashing. With celery running, and the current version of code on staging, this bug is not reproducible.

**Comment by maltman** [comment]
Agreed.

Though before closing -- do we know why celery crashed and how to
avoid in the future? if not, it seems like we need to add as a
separate issue.

On Wed, Dec 7, 2011 at 3:43 PM, David Zwarg
reply@reply.github.com
wrote:

**Comment by dzwarg** [comment]
One of the upgrade steps from the starting version (2.1.4?) to the current version (2.2.3) was skipped, and celery would appear to run when the service was started, but the logs would indicate a failure. It was an oversight on upgrade, and is a resolved issue.

The steps are fully documented in [Upgrade Software Versions](https://github.com/PublicMapping/DistrictBuilder/wiki/Upgrade-Software-Versions) on the wiki.

**Comment by maltman** [comment]
Great. Thanks.

On Thu, Dec 8, 2011 at 9:08 AM, David Zwarg
reply@reply.github.com
wrote:

> One of the upgrade steps from the starting version (2.1.4?) to the current version (2.2.3) was skipped, and celery would appear to run when the service was started, but the logs would indicate a failure. It was an oversight on upgrade, and is a resolved issue.
> 
> The steps are fully documented in [Upgrade Software Versions](https://github.com/PublicMapping/DistrictBuilder/wiki/Upgrade-Software-Versions) on the wiki.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/PublicMapping/DistrictBuilder/issues/256#issuecomment-3062696

## 

---

Micah Altman, Ph.D. http://redistricting.info           Twitter: @drmaltman
Senior Research Scientist, Institute for Quantitative Social Science, Harvard U.
Director of Archiving and Acquisitions, IQSS;
"Entia non sunt multiplicanda sine necessitate" - Dr. Invincibilis
(Corollary, "Ad indicia spectate.")
