### ISSUE TITLE
Possible to add social icons/links to share tab? 

### ISSUE THREAD

**Issue by maltman** [PublicMapping/districtbuilder-classic#257]
Now that we have figured out the social button/link stuff would it be hard to add 

 Facebook/G+/Twitter/Wordpress/Blogger icon/links to the share tab so that people could share their plans easily?

**Comment by maltman** [comment]
Appears completed. Is there anything left?

**Comment by briantjacobs** [comment]
No, we're all set with this one. I'll close it out.
