### ISSUE TITLE
Cannot edit shared plan

### ISSUE THREAD

**Issue by maltman** [PublicMapping/districtbuilder-classic#263]
Share a plan. 

Go to my plans in plan chooser. 

Choose the shared plan

Choose "edit selected" 

Draw tab allows viewing only, no editing tools enabled.

**Comment by dzwarg** [comment]
Confirmed, but not a bug. Shared plans cannot be edited, and haven't been editable before. This is the way shared plans have been designed.

If a user would like to edit a shared plan, they may return to the original plan (from which the shared plan originated), and continue editing that plan.

**Comment by maltman** [comment]
Ok. Accepted that shared plans are still not intended to be editable,
then UI not read "edit selected plan" (see
http:whe//www.box.com/s/3fzzfcd85yh13zt5cb4s )
when shared plan are selected: We could rename to "View selected
plan.", or disable in this case.

On Thu, Dec 8, 2011 at 9:10 AM, David Zwarg
reply@reply.github.com
wrote:

> Confirmed, but not a bug. Shared plans cannot be edited, and haven't been editable before. This is the way shared plans have been designed.
> 
> If a user would like to edit a shared plan, they may return to the original plan (from which the shared plan originated), and continue editing that plan.
