### ISSUE TITLE
Auth error should redirect to login

### ISSUE THREAD

**Issue by maltman** [PublicMapping/districtbuilder-classic#269]
This is a regression.

Log out. 

Follow a link to a non-shared plan:
http://gmu.azavea.com/districtmapping/plan/108/view/

Result:

AttributeError debug trace

Expected result:

Redirect to login (preferably with informative message about you must login as the author view this plan...)

**Comment by maltman** [comment]
Not on GMU.azavea yet? Still reproduces there...

**Comment by dzwarg** [comment]
Just pulled changes from github onto staging. Please try again.

**Comment by maltman** [comment]
Still tests broken, see http://www.box.com/s/yl7bd42l2eqy9uxqcx7a

**Comment by dzwarg** [comment]
This is a slightly different error message; I'll reopen because it is an error.

**Comment by dzwarg** [comment]
Related to this django bug: https://code.djangoproject.com/ticket/16147
