### ISSUE TITLE
Upload Plan: Email address handling

### ISSUE THREAD

**Issue by maltman** [PublicMapping/districtbuilder-classic#273]
1. Email address should be optional (for privacy reasons) -- currently mandatory. 
2. If account is associated with an e-mail account, that value should be pre-filled -- why make user type it again?

**Comment by dzwarg** [comment]
If the account has an email address, the email address field does not appear -- it is implicitly pre-filled. If a user has an email address on their account, they do not have to enter in their address again.

**Comment by maltman** [comment]
Ok. Though see http://www.box.com/s/zqcyjgnr55clhll7zmzl for a reproducible issue in which the e-mail address is entered, but not implicitly pre-filled. Refreshing subsequently logging in/out produced the behavior  you describe.

**Comment by dzwarg** [comment]
Confirmed.

The sequence of operations that are illustrated above do indeed present the user with a strange situation (i.e. "I entered my email address but it still complains."), but the instructions request that the user enter their email address as part of the upload form. To bypass that field, and go straight to the user account form is somewhat quirky and (I would argue) unusual.

I will leave this as an open bug, but mark it as low priority.

**Comment by maltman** [comment]
Some of us don't like to enter forms more than once :-)  I wasn't
intending to break it in QA ... that was my natural approach. Does
that make me "quirky"? (Possibly :-) One of my other QA'ers ran into
this too, but that may be a result of thinking like a QA person. But
we can assume part two of this issue is low priority, pending repeated
complaints from users.

That leaves part 1 of the issue. E-mail is supposed to be recommended,
but not required. We can warn if there is no e-mail set, but user
should still be able to  upload w/out it.

On Thu, Dec 8, 2011 at 9:14 AM, David Zwarg
reply@reply.github.com
wrote:

> Confirmed.
> 
> The sequence of operations that are illustrated above do indeed present the user with a strange situation (i.e. "I entered my email address but it still complains."), but the instructions request that the user enter their email address as part of the upload form. To bypass that field, and go straight to the user account form is somewhat quirky and (I would argue) unusual.
> 
> I will leave this as an open bug, but mark it as low priority.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/PublicMapping/DistrictBuilder/issues/273#issuecomment-3062767

## 

---

Micah Altman, Ph.D. http://redistricting.info           Twitter: @drmaltman
Senior Research Scientist, Institute for Quantitative Social Science, Harvard U.
Director of Archiving and Acquisitions, IQSS;
"Entia non sunt multiplicanda sine necessitate" - Dr. Invincibilis
(Corollary, "Ad indicia spectate.")

**Comment by dzwarg** [comment]
While an email is recommended for the application, this features requires an email address in case there is an error in the upload or importing. Without an email address, there is no way to communicate to the user if there was a problem with their upload. 

Removing this requirement may lead to a poor user experience if a file cannot be uploaded, as it would seem to 'disappear' when uploaded, as no plan would be created, and the user would have no feedback as to the success or failure of their uploaded plan.

**Comment by dzwarg** [comment]
While an email is recommended for the application, this features requires an email address in case there is an error in the upload or importing. Without an email address, there is no way to communicate to the user if there was a problem with their upload. 

Removing this requirement may lead to a poor user experience if a file cannot be uploaded, as it would seem to 'disappear' when uploaded, as no plan would be created, and the user would have no feedback as to the success or failure of their uploaded plan.

**Comment by maltman** [comment]
Yes, this improves the user experienced, hence it is  fine for a mechanism
to "recommended" the email address as per the ticket. However it is a
violation of default privacy policies, which are themselves based on the
requirement to allow full use of system w/out identifying info (which
e-mail addresses are per EU and US law). We can have a "confirm" dialog if
you like for usability, but in the end, the user must have the option to
load data without providing an e-mail address. Needs to be reopened and
fixed.

On Tue, May 29, 2012 at 3:12 PM, David Zwarg <
reply@reply.github.com
