### ISSUE TITLE
Locked District Boundaries do not show clearly

### ISSUE THREAD

**Issue by maltman** [PublicMapping/districtbuilder-classic#278]
Outline of locked district should show in red. However, selecting a single district and locking it only shows part of boundary in red.

See: http://www.box.com/s/ctr3fmokk3dz1gtnxayd

**Comment by abbyfretz** [comment]
The simultaneous display of multiple boundary layers gets more problematic the more boundaries we display. Brian will review to see if we might further adjust transparencies, colors, etc.
