### ISSUE TITLE
Add NOTICE and attribution statements to source tree

### ISSUE THREAD

**Issue by abbyfretz** [PublicMapping/districtbuilder-classic#291]

**Comment by dzwarg** [comment]
Completed. Commits:
- d952f9b51f2cdaeb54b329f6016396dc683a6914
- dca810531c41f1b4aa61837ef010799c213978d2
- db2d17eff93390397e64d5509cd801ab2ba26ef2
- 5f16d68271b66aacce010c506c46b77c635cbc57

All 3rd party libraries now contain their respective COPYRIGHT notices.
