### ISSUE TITLE
Document changes needed to config.xml after subject addition

### ISSUE THREAD

**Issue by andrewjennings** [PublicMapping/districtbuilder-classic#305]
After adding a new subject through the data tools, the user needs to align their config.xml with the current configuration.

**Comment by dzwarg** [comment]
I created a wiki page that describes the config synchorization process: [wiki/Synchronize-Configuratior](https://github.com/PublicMapping/DistrictBuilder/wiki/Synchronize-Configuration)

This page is referenced in the Subject manipulation docs, i.e. [Add a Subject](https://github.com/PublicMapping/DistrictBuilder/wiki/Add-a-Subject) and [Modify a Subject](https://github.com/PublicMapping/DistrictBuilder/wiki/Modify-a-Subject).

**Comment by maltman** [comment]
The current documentation, although it warns of the necessity to synchronize, does not seem to be sufficient on its face to enable an administrative user to actually do any synchronization.

There are two cases:

The simple case:
- If the admin has just added/modified a subject, and knows what they entered in the interface -- what are each of the steps that they need to make to modify config.xml? For example -- how do each of the form elements or template elements correspond to each of the config elements?

The most important case, for replication, reproducibility, portability: 
- If some unknown number of changes has been made through the admin interface:
  - how does one determine exactly which config elements are inconsistent
  - how does one determine which config elements are  missing
  - what database queries does one use to determine the correct values to be put in the config file for each element

Thanks,

**Comment by dzwarg** [comment]
Documented two use-cases as examples/tutorials at the bottom of the wiki page [Synchronize-Configuration](https://github.com/PublicMapping/DistrictBuilder/wiki/Synchronize-Configuration).  One use case is for when a new subject is added, and the other is for when an administrator is checking for changes.
