### ISSUE TITLE
"Select" fix is not displaying

### ISSUE THREAD

**Issue by abbyfretz** [PublicMapping/districtbuilder-classic#319]
Solution implemented for "select", such as "Select Rectangle" is not working (line 801). The French translation is not appearing on screen, only the English text.

**Comment by andrewjennings** [comment]
A lot of these entries had been marked as "fuzzy" by django.  That means they need some additional review.  They don't get pulled into templates.

I removed the "fuzzy" entries.  In the future, please just remove the "fuzzy" line from the translation files if you're sure of it.
