### ISSUE TITLE
Internationalization: Use of "Community" and "District" Text Variables

### ISSUE THREAD

**Issue by mcdisc** [PublicMapping/districtbuilder-classic#322]
Some displayed text such as "District Tools" and "Community Tools" are actually a variable string = "District" or "Community" that is concatenated with the text "Tools", depending if the user has selected a community map or a map with districts to draw. While this is a simple case, there are more complex cases where the variable shows up in a sentence in a tool tip.

This is problematic for language translation since the word District or Community may need to be translated differently depending on the context of its usage.

The solution is to have separate strings to display for "District Tools" and "Community Tools".

**Comment by andrewjennings** [comment]
Fixed this by using formatted python strings. E.g.,  "{{ district_label }} Tools" can be "Tools de {{ district_label }}" or similar.  See #357 for examples and a link to the fix.
