### ISSUE TITLE
Selected geographies not working

### ISSUE THREAD

**Issue by mcdisc** [PublicMapping/districtbuilder-classic#323]
While working on new documentation, selection of geographies stopped working. The selection tool started working again when I clicked the "Click and Drag" icon. I cannot replicate the steps leading to this failure at this time. I will post an update if I can replicate.

**Comment by andrewjennings** [comment]
In order to fix this bug, we need steps to reproduce it.

**Comment by mcdisc** [comment]
I believe that this bug was related to district locking failure. It may been cleared up by a re-configuration of the software since it is working now. I was able to select geographies when I tested the multimember feature.

# 

Dr. Michael P. McDonald
Associate Professor, George Mason University
Non-Resident Senior Fellow, Brookings Institution

```
                         Mailing address:
```

(o) 703-993-4191             George Mason University
(f) 703-993-1399             Dept. of Public and International Affairs
mmcdon@gmu.edu               4400 University Drive - 3F4
http://elections.gmu.edu     Fairfax, VA 22030-4444

-----Original Message-----
