### ISSUE TITLE
html() method in redistricting/calculators.py not I8n

### ISSUE THREAD

**Issue by maltman** [PublicMapping/districtbuilder-classic#345]
Appears to use untranslated text.

**Comment by dzwarg** [comment]
It looks like the Interval calculator is the only one that doesn't use i18n properly:

https://github.com/PublicMapping/DistrictBuilder/blob/master/django/publicmapping/redistricting/calculators.py#L1331

**Comment by andrewjennings** [comment]
The numbers are being properly formatted in the sidebars.  The interval calculator only uses words in the context of CSS class names (even, odd, interval_x) so I think those should be left as-is.

If there's a specific place where this behavior happens, please file a bug and we'll fix the calculator.
