### ISSUE TITLE
New user registration japanese terms of use

### ISSUE THREAD

**Issue by maltman** [PublicMapping/districtbuilder-classic#354]
Appear incompletely translated into Japanese (on gmu instance)

**Comment by andrewjennings** [comment]
It's incompletely translated in the original file I received.  Looks as if the japanese file was copied from the Spanish file; Which means that when the user selects "Japanese" in the language menu, they'll receive a mix of Japanese, English and Spanish.
Unknown translations should be left blank so they're filled in with the default English msgid.

**Comment by dzwarg** [comment]
This has been resolved in v2.0 branch.

**Comment by dzwarg** [comment]
Also fixed on staging.
