### ISSUE TITLE
-es added to "district" in spanish

### ISSUE THREAD

**Issue by michaelsanders00** [PublicMapping/districtbuilder-classic#360]
In a few places in the program, -es is added on the end of "district" (or "distrito" in spanish). This leaves "distritoes" which is an incorrect spelling. It should be 'distritos"

one example of this is found at line 859 of the code.
(this shows in the program where you hover over "click and drag")

**Comment by andrewjennings** [comment]
We use a library called inflect.py to pluralize words.  It looks as if it follows English rules.  I'll see if there's an alternative.

**Comment by michaelsanders00** [comment]
I guess it's because english words that end in an o are usually pluralized with -es (like dominoes). However, in spanish, words that end in a vowel are pluralized just by adding -s

However, words that end in a consonant in spanish are actually pluralized with -es (in english it would just be -s)

not sure if that's helpful...
