### ISSUE TITLE
Multi-member update district and plan level target population

### ISSUE THREAD

**Issue by mcdisc** [PublicMapping/districtbuilder-classic#363]
The target population for a multi-member district is [target population for a single district] \* [number of members]. The target population for an individual district should change when the number of members is changed. For example if the target population is 50,000 and a district with one member has 100,000 persons, it is over-populated by 50,000 persons. If two members are assigned to the district, it has exactly equal population. If it is assigned three members, it is under-populated by 50,000- (100,000/3) = 16,667. 

The plan level statistics should also update. In the example, if there are 100 districts in the plan and the example district is assigned  1 member, 0 of 100 districts meet target population. If the district is assigned 2 members, 1 of 99 meet target population. If the district is assigned 3 members, 0 of 98 meet target population.

**Comment by andrewjennings** [comment]
We discussed this and decided the behavior in the sidebar should not be changed but that it would be helpful to have an indicator for each district in the sidebar to make it easier to "figure out" why a multi-member district would be valid/invalid for a given calculator.  That task is issue #396
