### ISSUE TITLE
Multi-member copy and paste bug

### ISSUE THREAD

**Issue by mcdisc** [PublicMapping/districtbuilder-classic#364]
Attempted to copy and paste a 3 member district from State House Test (only district in that plan) into Test House 2 (the "current" districts minus unassigned House district 24). Received a "sorry unable to paste districts" message. The program then gave a "please wait, computing new districts" message and froze. When I restarted the program, the paste did not take place. (i also tried pasting the district into a blank plan, "House Test 3", with the same results.

In general, we need to decide how to handle copy and paste in the multi-member context. If a district is copied into a plan such that the resulting plan exceeds the maximum number of members, how should this be handled? Should we prohibit the copy, with an error message that the number of members has been exceeded? Should we allow the copy, but set the number of members of the copied district to 1? Should we always set the number of members of the copied district equal to 1, with a message that the user should assign the desired number of members (this seems clunky to me, but may be a logical solution)?

**Comment by andrewjennings** [comment]
There was a larger issue with cut-and-paste and i18n that this helped me find.  I also updated the behavior to simply copy the number of members for the original plan.  Right now, a plan is allowed to have more than the maximum number of allowed members while it's in progress so copying and pasting extra members isn't a problem.
