### ISSUE TITLE
New subject does not detect malformed files correctly

### ISSUE THREAD

**Issue by maltman** [PublicMapping/districtbuilder-classic#371]
-  if the input file is missing columns --> throws 500/oops/unknown error
-  if additional columns -> behaves as 370 (does not report wrong number of columns)
-  if first column not labeled "geoid" ->  processes for 40 minutes, fails with:

"Renested foundation geographies, creating spatial views and styles...

Sorry! This processing step failed with the following error message: Transaction managed block ended with pending COMMIT/ROLLBACK"

**Comment by dzwarg** [comment]
Fixed issue with missing columns. (1ed6a5f)
