### ISSUE TITLE
Add New Subject Does not Handle Invalid Name Correctly

### ISSUE THREAD

**Issue by maltman** [PublicMapping/districtbuilder-classic#372]
- Does correctly ask for new name
- then reports that subject has been ingested successfully, and prompts to "Continue"
- However, continue leads to 500 error, and subject is not added in subject admn

**Comment by dzwarg** [comment]
Can you provide an example of an "Invalid Name"?

The subject upload should work with these permutations of what I thought an "Invalid Name" could be:
- All symbols: **}{)(*&^%$#@!~?+|<>**
- Empty string
- Mix of symbols and text: **this*is!an&invalid&lt;subject&gt;name**

**Comment by maltman** [comment]
I tried "$$$$$$$" - Micah

**Comment by dzwarg** [comment]
Confirmed that this does not happen in HEAD of v2.0-rc
