### ISSUE TITLE
Add New Subject Concurrency Issues

### ISSUE THREAD

**Issue by maltman** [PublicMapping/districtbuilder-classic#379]
In http://gmu.azavea.com/admin/redistricting/subject/upload/ verification stage is a lengthy operation, during that time:
- appears that if another subject is added concurrently both subject additions eventually fail (although this could be a symptom of a different bug, since most subject additions were failing)

**Comment by dzwarg** [comment]
Adding two subjects at the same time works with no errors with HEAD of v2.0-rc
