### ISSUE TITLE
Add New Subject and back button

### ISSUE THREAD

**Issue by maltman** [PublicMapping/districtbuilder-classic#380]
After previous reported failures, "back" button must be used to return to interface -- as 500 error does not provide interface menus.

Back-ing into Upload page appears to restart "processing" sequence, but hangs at first step (probably JavaScript issue?)

**Comment by dzwarg** [comment]
All errors should handle upload process gracefully, so no 500 errors should appear. If a specific set of actions causes the 500 error to appear, please open a new issue with steps to follow in order to reproduce the problem.
