### ISSUE TITLE
Administrative User cannot Reaggregate Individual Plans

### ISSUE THREAD

**Issue by maltman** [PublicMapping/districtbuilder-classic#384]
Test2 has admin privileges, but still cannot reaggregate plans shared by others or originally provided templates.

**Comment by maltman** [comment]
To clarify as per 386, need to be able to reaggregate both (a) selected plans; (b) all submitted plans (not necessarily shared); (c) all shared plans.

**Comment by dzwarg** [comment]
Administrators have this capability in the `/admin/` area of the site, but not the public plan chooser.
