### ISSUE TITLE
Reaggregation is undocumented

### ISSUE THREAD

**Issue by maltman** [PublicMapping/districtbuilder-classic#386]
- No documentation on what admin user needs to do after subject upload to return system to a usable state (all published plans reaggregated, leaderboards consistent, templates usable)
- No end-user documentation on what reaggregate does, why it is necessary, and what "Update leaderboards" does

**Comment by dzwarg** [comment]
Added reaggregation wiki page, linked from "Add a Subject" page, and the "Documentation" page, under the "Maintenance" section.
