### ISSUE TITLE
Update Leaderboards With working Plan Fails

### ISSUE THREAD

**Issue by maltman** [PublicMapping/districtbuilder-classic#388]
Update Leaderboards With working Plan Fails

**Comment by andrewjennings** [comment]
Micah, could you please share the valid plan?  I don't have a valid plan to submit.  If I attempt to submit an invalid plan, I get the expected "Validation failed" message.  Thanks.

**Comment by maltman** [comment]
- Mike's plan is listed on the public leaderboard & shared, shouldn't it be valid? I made a copy and attempted to revalidate... this failed.
- I'd expected this feature to update the leaderboard with currently leading plans (to refresh) ... instead it complained about validation of the current (?) plan... maybe this is an incorrect expectation, I'll file a separate issue

**Comment by dzwarg** [comment]
Publicly shared plans currently cannot be submitted to the leaderboard. Any publicly shared plan on the leaderboard is owned by a user. I looked at the current leaderboard, and I see "Mike's Congressional plan", which appears to be valid, but the only shared plan is "Mike's Congressional" -- I believe these are two different plans.

Editing a plan to be valid and submitting to the leaderboard works as expected, and I cannot find any errors in the validation process or the UI around submitting the currently working plan to the leaderboard.
