### ISSUE TITLE
Undo not working after cut and paste

### ISSUE THREAD

**Issue by mcdisc** [PublicMapping/districtbuilder-classic#404]

**Comment by dzwarg** [comment]
Just tested this, and cannot reproduce. Performed the following actions:
- From a new plan, move a few small geographies between districts
- Navigate backward with 'undo'
- Navigate forward with 'redo'
- Unassign a district
- Navigate backward with 'undo'
- Navigate forward with 'redo'
- Copy & paste a new district into the space where the old one was
- Navigate backward with 'undo'
- Navigate forward with 'redo'

Any other steps to reproduce?
