### ISSUE TITLE
Add QuickHull Compactness score

### ISSUE THREAD

**Issue by jbranigan** [PublicMapping/districtbuilder-classic#429]
- Add calculator
- Update docs
- Add tests

**Comment by dzwarg** [comment]
Calculator added in 025e270bf4c07c59e0611692d5a5e28712b11e15
Tests added in 025e270bf4c07c59e0611692d5a5e28712b11e15

**Comment by dzwarg** [comment]
Tested and verified rev 025e270bf4c07c59e0611692d5a5e28712b11e15

**Comment by jbranigan** [comment]
Enable and re-run configuration setup.
