### ISSUE TITLE
Data Exports broken

### ISSUE THREAD

**Issue by dzwarg** [PublicMapping/districtbuilder-classic#434]
Sometimes the data exports are broken on the 2.0 AMI. Fix.

**Comment by dzwarg** [comment]
This is a simple fix where the URL of the site needs to be configured in the django admin interface when instantiating a new AMI.

**Comment by dzwarg** [comment]
Fix instructions: [Data Export](https://github.com/PublicMapping/DistrictBuilder/wiki/Data-Export) wiki page

**Comment by jbranigan** [comment]
Still experiencing problems with this functionality.

**Comment by wboykinm** [comment]
Not sure if it's related, but the print option [times out with no error in the log](http://btvvotes.org/districtmapping/plan/294/view/).
