### ISSUE TITLE
Docker deployment?

### ISSUE THREAD

**Issue by msarahan** [PublicMapping/districtbuilder-classic#454]
I attended the MGGG workshop in Boston, and I would like to help make this project easier to deploy.  Based on my experience and studying your install directions, I think that breaking your instructions up into the following pieces might be the right way to go:

1. postgres + postgis docker image (based on https://hub.docker.com/r/mdillon/postgis/)
2. Apache httpd + python docker image
3. Geoserver docker image (based on https://hub.docker.com/r/kartoza/geoserver/)

Numbers 1 and 3 seem already quite close to what we need out-of-the-box.  Number 2 will involve adding a significant amount of software and installing DistrictBuilder itself.

These three could/would be linked and deployed together by a docker-compose file.  I think we could get deployment time down well below your 80 minute target.

I would like to undertake this work, but before I do, I wanted to make sure that you'd be receptive to this scheme.  If you'd like to discuss the design further, we can do it here or on a Google Hangout.

**Comment by themightychris** [comment]
Check out my (unofficial fan) work on #453 to containerize DistrictBuilder

Habitat is a new way to automate the build process and service lifecycle of apps from the Chef team. It makes apps topology and OS independent so you can deploy them via docker containers and docker-compose or all on the same metal just the same.

I've been using it for a while now and it delivers on the dream and would make DistrictBuilder super quick to deploy and drastically simplify long term development and maintenance. In the course of my trying to get DistrictBuilder running I've contributed a PostGIS plan that some folks have been using in production under docker already: https://github.com/habitat-sh/core-plans/pull/682

This big barrier I've run into is the that django app and dep situation is fubar and I don't know that ecosystem at all. I can churn out habitat plans to build exact environments for all the components if someone can help get the dang python app able to run again

**Comment by msarahan** [comment]
Many thanks @themightychris!  Glad I posted here - you have a great start.  Python is my wheelhouse, though not django so much.  I'll dig in and see what I can do.  I'll submit PR's to your branch that #453 is based on.

**Comment by themightychris** [comment]
@msarahan if you know Python I imagine master is the best place to start, which is what that pull request is based off of. I got frustrated with playing whackamole with all the pip modules and started another branch starting from the v2.0 tag to see if that would have a better dep chain but ground to the same halt.

It might be helpful to skim through my commits on both branches, there might be problems solved on the v2 branch that weren't on the master one, but I also didn't know enough about what I was doing to python to really know where I was solving problems vs creating new ones

If you're going to take a stab at working with habitat I'd be happy to jump on a call to provide support or help you get oriented. I'm also available most of the time on Code for Philly's public slack, I have a channel open for this: https://codeforphilly.org/chat/districtbuilder
