### ISSUE TITLE
Update external deployment documentation

### ISSUE THREAD

**Issue by dsummersl** [PublicMapping/districtbuilder-classic#544]
#### Problem description

The terraform template 'sample.tfvars' referenced in deployment/README.md does not exist. It would be helpful to have this when creating new deployments.

**Comment by dsummersl** [comment]
The script `scripts/terra` also appears to be missing.

**Comment by hectcastro** [comment]
Hey @dsummersl, sorry for the delayed response.

We are in the middle of a bit of a transition with regard to how we plan to support external District Builder deployments. Internally, we make use of AWS, Terraform, Ansible, and Docker to facilitate District Builder instance deployment—but that approach is very specific to how our internal infrastructure is setup.

For open source users, we think focusing on and documenting a more straightforward Docker/Docker Compose based deployment approach will be more successful. It is a lot less involved and opinionated, but is still a component of our overall internal deployment process (we'll be eating our own dog food).

Parts of the transition referenced above is in-progress as part of https://github.com/PublicMapping/DistrictBuilder/issues/542. In addition to that, this issue will be used to track when the associated documentation is updated.

**Comment by dsummersl** [comment]
@hectcastro thanks so much for the response and suggestion - we are still very much in the phase of creating or NC based configuration files. But I wanted to get a head start on the deployment side; I'll keep monitoring tickets here that you suggest in the meantime...
