### ISSUE TITLE
Migrate DTL infrastructure and deployment changes

### ISSUE THREAD

**Issue by hectcastro** [PublicMapping/districtbuilder-classic#554]
#### Problem description

As part of the process of standing up the DTL instance of DistrictBuilder, we made a handful of infrastructure and deployment changes. Ensure that those are ported to this repository.

- `variables.tf`
- CloudWatch Logs configuration via `cloud-config`
- Private DNS records for application server
- Remove CloudFormation JSON
- Add CI override file for Docker Compose
- Use centrally managed Geoserver container image (`FROM quay.io/azavea/geoserver:2.11.2-tomcat9-jre8-slim)`
- Various changes in `scripts`
- ...

#### Replication Steps

- Diff the two repositories
- Note all of the differences

#### Expected Behavior or Output

- All of the desirable changes are reconciled

**Comment by rbreslow** [comment]
Jean and I paired this afternoon. This is what we have so far: https://github.com/PublicMapping/DistrictBuilder/compare/develop...azavea:feature/jrb/infra-update?expand=1

**Comment by jeancochrane** [comment]
A note on our process: We decided to cherry pick Taylor's commits (which seemed from a quick scan to be a reasonable approximation of "all infrastructure commits") and rebase them back onto the point at which `azavea/district-builder-dtl-pa` diverged from `PublicMapping/DistrictBuilder`. Then, we merged that branch into `PublicMapping/DistrictBuilder` to bring it up to date with the current state of the repo.
